#!/usr/bin/env bash
# One-shot deploy: Jetson runtime + signaling + Tailscale + config + systemd.
# Usage:
#   chmod +x bootstrap.sh && ./bootstrap.sh
#   ./bootstrap.sh --with-dashboard       # also build & run caregiver UI on :3000
#   ./bootstrap.sh --no-start             # install only, do not systemctl start
#   ./bootstrap.sh --no-tailscale         # skip Tailscale (LAN-only)
#
# Unattended Tailscale join (optional):
#   TAILSCALE_AUTH_KEY=tskey-auth-xxx ./bootstrap.sh
set -euo pipefail

ROOT="$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" && pwd)"
cd "$ROOT"

WITH_DASHBOARD=false
WITH_TAILSCALE=true
START_NOW=true
for arg in "$@"; do
  case "$arg" in
    --with-dashboard) WITH_DASHBOARD=true ;;
    --no-tailscale) WITH_TAILSCALE=false ;;
    --no-start) START_NOW=false ;;
    -h|--help)
      cat <<'EOF'
Usage: ./bootstrap.sh [--with-dashboard] [--no-start] [--no-tailscale]

  --with-dashboard   Build and run the Next.js caregiver UI on :3000
  --no-start         Install only; do not systemctl enable/start
  --no-tailscale     Skip Tailscale install (same-Wi-Fi / LAN only)

Environment (optional):
  TAILSCALE_AUTH_KEY   One-time auth key from Tailscale admin console
  TAILSCALE_HOSTNAME   Tailnet device name (default: kineticpulse-jetson)
EOF
      exit 0
      ;;
    *)
      echo "Unknown option: $arg (try --help)" >&2
      exit 1
      ;;
  esac
done

echo "=============================================="
echo " KineticPulse one-shot bootstrap"
echo " Repo: $ROOT"
echo "=============================================="

# --- 1) Python edge runtime (venv, weights check, kineticpulse launcher) ---
bash "$ROOT/deploy/jetson/install.sh"

# --- 2) Node.js for signaling (and optional dashboard) ---
ensure_node() {
  if command -v node &>/dev/null; then
    local major
    major="$(node -p "process.versions.node.split('.')[0]")"
    if [[ "$major" -ge 18 ]]; then
      return
    fi
    echo "==> Node.js $(node -v) is too old; installing Node 20..."
  fi
  if command -v apt-get &>/dev/null; then
    if ! command -v node &>/dev/null || [[ "$(node -p "process.versions.node.split('.')[0]")" -lt 18 ]]; then
      curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
      sudo DEBIAN_FRONTEND=noninteractive apt-get install -y nodejs
    fi
  else
    echo "ERROR: Node.js 18+ required for signaling. Install node and re-run." >&2
    exit 1
  fi
}

ensure_node
echo "==> Node $(node -v)"

echo "==> Installing dashboard/signaling npm deps..."
(cd "$ROOT/dashboard" && npm install)

# --- 2b) Tailscale (default: on — remote caregivers without a paid VPS) ---
install_tailscale() {
  if [[ "$WITH_TAILSCALE" != true ]]; then
    echo "==> Skipping Tailscale (--no-tailscale)"
    return
  fi
  echo "==> Installing Tailscale (free mesh VPN for off-LAN caregivers)..."
  if ! command -v tailscale &>/dev/null; then
    curl -fsSL https://tailscale.com/install.sh | sh
  else
    echo "    Already installed: $(tailscale version 2>/dev/null | head -1 || echo tailscale)"
  fi
  sudo systemctl enable --now tailscaled 2>/dev/null || true

  if tailscale status &>/dev/null 2>&1; then
    echo "    Connected: $(tailscale ip -4 2>/dev/null || echo '?')"
    return
  fi

  local hostname="${TAILSCALE_HOSTNAME:-kineticpulse-jetson}"
  if [[ -n "${TAILSCALE_AUTH_KEY:-}" ]]; then
    echo "==> Joining tailnet (TAILSCALE_AUTH_KEY)..."
    sudo tailscale up --auth-key="$TAILSCALE_AUTH_KEY" --hostname="$hostname"
  else
    echo ""
    echo "==> Tailscale installed but not on your tailnet yet."
    echo "    Run once on this Jetson (browser login or copy the URL):"
    echo "      sudo tailscale up --hostname=$hostname"
    echo "    Or re-run with a one-time key from https://login.tailscale.com/admin/settings/keys :"
    echo "      TAILSCALE_AUTH_KEY=tskey-auth-... ./bootstrap.sh"
    echo ""
  fi
}

caregiver_reachable_host() {
  if [[ "$WITH_TAILSCALE" == true ]] && command -v tailscale &>/dev/null; then
    local ts_ip
    ts_ip="$(tailscale ip -4 2>/dev/null || true)"
    if [[ -n "$ts_ip" ]]; then
      echo "$ts_ip"
      return
    fi
  fi
  echo "${KINETICPULSE_LAN_IP:-127.0.0.1}"
}

install_tailscale

# --- 3) Deploy secrets (stable across re-runs) ---
mkdir -p "$ROOT/deploy/handoff"
SECRETS_FILE="$ROOT/deploy/.env.deploy"
if [[ ! -f "$SECRETS_FILE" ]]; then
  LAN_IP="$(hostname -I 2>/dev/null | awk '{print $1}')"
  [[ -z "$LAN_IP" ]] && LAN_IP="127.0.0.1"
  JETSON_TOKEN="$(openssl rand -hex 24)"
  CAREGIVER_TOKEN="$(openssl rand -hex 24)"
  cat > "$SECRETS_FILE" <<EOF
# Generated by bootstrap.sh — do not commit
JETSON_SIGNAL_TOKEN=$JETSON_TOKEN
CAREGIVER_SIGNAL_TOKEN=$CAREGIVER_TOKEN
SIGNAL_HOST=0.0.0.0
SIGNAL_PORT=8787
KINETICPULSE_LAN_IP=$LAN_IP
EOF
  chmod 600 "$SECRETS_FILE"
  echo "==> Created $SECRETS_FILE"
else
  echo "==> Reusing existing $SECRETS_FILE"
fi

# shellcheck disable=SC1090
set -a && source "$SECRETS_FILE" && set +a

CAREGIVER_HOST="$(caregiver_reachable_host)"
TAILSCALE_IP=""
if command -v tailscale &>/dev/null; then
  TAILSCALE_IP="$(tailscale ip -4 2>/dev/null || true)"
fi

# --- 4) Wire config.yaml + caregiver handoff ---
source "$ROOT/.venv/bin/activate"
python3 "$ROOT/deploy/scripts/write_deploy_config.py" "$ROOT"

cat > "$ROOT/deploy/handoff/caregiver.env" <<EOF
# Copy to dashboard/.env.local on a caregiver laptop/phone (same tailnet).
# Caregivers must install Tailscale: https://tailscale.com/download
NEXT_PUBLIC_SIGNALING_HTTP_BASE=http://${CAREGIVER_HOST}:${SIGNAL_PORT}
NEXT_PUBLIC_SIGNALING_WS_BASE=ws://${CAREGIVER_HOST}:${SIGNAL_PORT}/ws
NEXT_PUBLIC_CAREGIVER_TOKEN=${CAREGIVER_SIGNAL_TOKEN}
EOF

cat > "$ROOT/dashboard/.env.local" <<EOF
NEXT_PUBLIC_SIGNALING_HTTP_BASE=http://${CAREGIVER_HOST}:${SIGNAL_PORT}
NEXT_PUBLIC_SIGNALING_WS_BASE=ws://${CAREGIVER_HOST}:${SIGNAL_PORT}/ws
NEXT_PUBLIC_CAREGIVER_TOKEN=${CAREGIVER_SIGNAL_TOKEN}
EOF

if command -v apt-get &>/dev/null; then
  sudo DEBIAN_FRONTEND=noninteractive apt-get install -y qrencode 2>/dev/null || true
fi
python3 "$ROOT/deploy/scripts/write_caregiver_handoff.py" "$ROOT" "$CAREGIVER_HOST"

# --- 5) Optional dashboard production build ---
if [[ "$WITH_DASHBOARD" == true ]]; then
  echo "==> Building caregiver dashboard (Next.js)..."
  (cd "$ROOT/dashboard" && npm run build)
fi

# --- 6) systemd units ---
DEPLOY_USER="$(id -un)"
NODE_BIN="$(command -v node)"
NPM_BIN="$(command -v npm)"

render_unit() {
  local template="$1"
  local dest_name="$2"
  sed \
    -e "s|@REPO_ROOT@|$ROOT|g" \
    -e "s|@DEPLOY_USER@|$DEPLOY_USER|g" \
    -e "s|@SECRETS_FILE@|$SECRETS_FILE|g" \
    -e "s|@NODE_BIN@|$NODE_BIN|g" \
    -e "s|@NPM_BIN@|$NPM_BIN|g" \
    "$template" | sudo tee "/etc/systemd/system/$dest_name" > /dev/null
}

echo "==> Installing systemd units..."
render_unit "$ROOT/deploy/systemd/kineticpulse-signaling.service.in" "kineticpulse-signaling.service"
render_unit "$ROOT/deploy/systemd/kineticpulse.service.in" "kineticpulse.service"

if [[ "$WITH_DASHBOARD" == true ]]; then
  render_unit "$ROOT/deploy/systemd/kineticpulse-dashboard.service.in" "kineticpulse-dashboard.service"
fi

sudo systemctl daemon-reload

if [[ "$START_NOW" == true ]]; then
  echo "==> Enabling and starting services..."
  sudo systemctl enable kineticpulse-signaling.service kineticpulse.service
  sudo systemctl restart kineticpulse-signaling.service
  sleep 1
  sudo systemctl restart kineticpulse.service
  if [[ "$WITH_DASHBOARD" == true ]]; then
    sudo systemctl enable kineticpulse-dashboard.service
    sudo systemctl restart kineticpulse-dashboard.service
  fi
fi

# --- 7) Smoke check signaling HTTP ---
sleep 1
if curl -sf -H "Authorization: Bearer ${CAREGIVER_SIGNAL_TOKEN}" \
  "http://127.0.0.1:${SIGNAL_PORT}/sessions" >/dev/null; then
  SIGNAL_OK="yes"
else
  SIGNAL_OK="no"
fi

SUMMARY="$ROOT/deploy/handoff/DEPLOY_SUMMARY.txt"
cat > "$SUMMARY" <<EOF
KineticPulse deploy summary
===========================
LAN IP:          ${KINETICPULSE_LAN_IP}
Caregiver host:  ${CAREGIVER_HOST}  (Tailscale IP if connected, else LAN)
$( [[ -n "$TAILSCALE_IP" ]] && echo "Tailscale IP:    ${TAILSCALE_IP}" )
Signaling HTTP:  http://${CAREGIVER_HOST}:${SIGNAL_PORT}/sessions
Signaling WS:    ws://${CAREGIVER_HOST}:${SIGNAL_PORT}/ws
Caregiver token: ${CAREGIVER_SIGNAL_TOKEN}
Jetson token:    ${JETSON_SIGNAL_TOKEN}  (in config.yaml webrtc.auth_token)

Tailscale (remote access, no extra server cost):
$( if [[ "$WITH_TAILSCALE" == true ]]; then
     if [[ -n "$TAILSCALE_IP" ]]; then
       echo "  Jetson is on the tailnet at ${TAILSCALE_IP}"
       echo "  Each caregiver: install Tailscale app → join same tailnet"
       echo "  Then use caregiver.env URLs above from any network"
     else
       echo "  Installed but not joined — run: sudo tailscale up --hostname=kineticpulse-jetson"
       echo "  Then re-run: ./bootstrap.sh  (refreshes caregiver URLs)"
     fi
   else
     echo "  Skipped (--no-tailscale). Caregivers must be on the same LAN."
   fi )

Services:
  sudo systemctl status kineticpulse-signaling
  sudo systemctl status kineticpulse
$( [[ "$WITH_DASHBOARD" == true ]] && echo "  sudo systemctl status kineticpulse-dashboard" )
$( [[ "$WITH_DASHBOARD" == true ]] && echo "  Dashboard UI: http://${CAREGIVER_HOST}:3000" )

Caregiver laptop / phone:
  1. Install Tailscale and join the team tailnet
  2. Install the KineticPulse mobile app (EAS/dev build — not Expo Go)
  3. Open app → Scan setup QR (file: deploy/handoff/caregiver-qr.png)
     or Server settings → paste deploy/handoff/caregiver.env
  4. Web dashboard: cp deploy/handoff/caregiver.env dashboard/.env.local && npm run dev

Headless Jetson (no monitor):
  Laptop on tailnet — open in browser (shows QR for phone to scan):
    http://${CAREGIVER_HOST}:${SIGNAL_PORT}/handoff?token=${CAREGIVER_SIGNAL_TOKEN}
  Or copy QR to your PC:
    scp ${DEPLOY_USER}@${KINETICPULSE_LAN_IP}:${ROOT}/deploy/handoff/caregiver-qr.png .
  SSH session during bootstrap also prints an ASCII QR when qrencode is installed.

Edge smoke test (no hardware):
  ./kineticpulse --mock-ble --mock-stt --no-camera --max-runtime-s 5

Signaling HTTP check after bootstrap: ${SIGNAL_OK}
EOF

echo ""
cat "$SUMMARY"
echo ""
echo "==> Headless QR (no monitor): open on a laptop on the tailnet:"
echo "    http://${CAREGIVER_HOST}:${SIGNAL_PORT}/handoff?token=${CAREGIVER_SIGNAL_TOKEN}"
echo "==> Bootstrap complete. Summary saved to deploy/handoff/DEPLOY_SUMMARY.txt"
